{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.fullname" . }}-auth
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $token := "" -}}
  {{- if .Values.auth.token -}}
    {{- $token = .Values.auth.token | b64enc -}}
  {{- else -}}
    {{- /* Пытаемся найти существующий секрет, чтобы не менять токен при обновлении */ -}}
    {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-auth" (include "openclaw.fullname" .))) -}}
    {{- if $existingSecret -}}
      {{- $token = index $existingSecret.data "gateway-token" -}}
    {{- else -}}
      {{- $token = randAlphaNum 64 | b64enc -}}
    {{- end -}}
  {{- end }}
  gateway-token: {{ $token | quote }}
{{- end }}